export interface SmorfiaMeaning {
  id: number;
  name: string;
}

export const smorfiaData: SmorfiaMeaning[] = [
  { id: 0, name: 'Huevos' },
  { id: 1, name: 'Agua' },
  { id: 2, name: 'Niño' },
  { id: 3, name: 'San Cono' },
  { id: 4, name: 'La cama' },
  { id: 5, name: 'Gato' },
  { id: 6, name: 'Perro' },
  { id: 7, name: 'Revolver' },
  { id: 8, name: 'Incendio' },
  { id: 9, name: 'Arroyo' },
  { id: 10, name: 'La Leche' },
  { id: 11, name: 'Minero' },
  { id: 12, name: 'Soldado' },
  { id: 13, name: 'La yeta' },
  { id: 14, name: 'Borracho' },
  { id: 15, name: 'Niña bonita' },
  { id: 16, name: 'Anillo' },
  { id: 17, name: 'Desgracia' },
  { id: 18, name: 'Sangre' },
  { id: 19, name: 'Pescado' },
  { id: 20, name: 'La Fiesta' },
  { id: 21, name: 'Mujer' },
  { id: 22, name: 'Loco' },
  { id: 23, name: 'Cocinero' },
  { id: 24, name: 'Caballo' },
  { id: 25, name: 'Gallina' },
  { id: 26, name: 'La Misa' },
  { id: 27, name: 'El Peine' },
  { id: 28, name: 'El Cerro' },
  { id: 29, name: 'San Pedro' },
  { id: 30, name: 'Santa Rosa' },
  { id: 31, name: 'La Luz' },
  { id: 32, name: 'Dinero' },
  { id: 33, name: 'Cristo' },
  { id: 34, name: 'La Cabeza' },
  { id: 35, name: 'Pajarito' },
  { id: 36, name: 'La Manteca' },
  { id: 37, name: 'El Dentista' },
  { id: 38, name: 'Piedras' },
  { id: 39, name: 'Lluvia' },
  { id: 40, name: 'El cura' },
  { id: 41, name: 'El cuchillo' },
  { id: 42, name: 'Zapatillas' },
  { id: 43, name: 'Balcón' },
  { id: 44, name: 'La Cárcel' },
  { id: 45, name: 'El vino' },
  { id: 46, name: 'Tomates' },
  { id: 47, name: 'Muerto' },
  { id: 48, name: 'Muerto habla' },
  { id: 49, name: 'La carne' },
  { id: 50, name: 'El Pan' },
  { id: 51, name: 'Serrucho' },
  { id: 52, name: 'Madre e hijo' },
  { id: 53, name: 'El Barco' },
  { id: 54, name: 'La vaca' },
  { id: 55, name: 'La Música' },
  { id: 56, name: 'La caída' },
  { id: 57, name: 'El jorobado' },
  { id: 58, name: 'Ahogado' },
  { id: 59, name: 'Las plantas' },
  { id: 60, name: 'La virgen' },
  { id: 61, name: 'Escopeta' },
  { id: 62, name: 'Inundación' },
  { id: 63, name: 'El casamiento' },
  { id: 64, name: 'El llanto' },
  { id: 65, name: 'El cazador' },
  { id: 66, name: 'Las lombrices' },
  { id: 67, name: 'La mordida' },
  { id: 68, name: 'Los sobrinos' },
  { id: 69, name: 'Los vicios' },
  { id: 70, name: 'Muerto sueño' },
  { id: 71, name: 'Excremento' },
  { id: 72, name: 'La sorpresa' },
  { id: 73, name: 'El hospital' },
  { id: 74, name: 'Gente negra' },
  { id: 75, name: 'Los besos' },
  { id: 76, name: 'Las llamas' },
  { id: 77, name: 'Pierna mujer' },
  { id: 78, name: 'La ramera' },
  { id: 79, name: 'El ladrón' },
  { id: 80, name: 'La bocha' },
  { id: 81, name: 'Las flores' },
  { id: 82, name: 'La pelea' },
  { id: 83, name: 'Mal tiempo' },
  { id: 84, name: 'La iglesia' },
  { id: 85, name: 'La linterna' },
  { id: 86, name: 'El humo' },
  { id: 87, name: 'Los piojos' },
  { id: 88, name: 'El Papa' },
  { id: 89, name: 'La rata' },
  { id: 90, name: 'El miedo' },
  { id: 91, name: 'El excusado' },
  { id: 92, name: 'El médico' },
  { id: 93, name: 'El enamorado' },
  { id: 94, name: 'El cementerio' },
  { id: 95, name: 'Los anteojos' },
  { id: 96, name: 'El marido' },
  { id: 97, name: 'La mesa' },
  { id: 98, name: 'La lavandera' },
  { id: 99, name: 'El hermano' },
];
