export interface SmorfiaMeaning {
  id: number;
  name: string;
}

// Datos unificados desde la version web. Este es ahora la fuente de verdad.
export const smorfiaData: SmorfiaMeaning[] = [
  { id: 0, name: 'Huevos' },
  { id: 1, name: 'Agua' },
  { id: 2, name: 'Niño' },
  { id: 3, name: 'San Cono' },
  { id: 4, name: 'La cama' },
  { id: 5, name: 'Gato' },
  { id: 6, name: 'Perro' },
  { id: 7, name: 'Revólver' },
  { id: 8, name: 'Incendio' },
  { id: 9, name: 'Arroyo' },
  { id: 10, name: 'La leche' },
  { id: 11, name: 'Palito' },
  { id: 12, name: 'Soldado' },
  { id: 13, name: 'La yeta' },
  { id: 14, name: 'Borracho' },
  { id: 15, name: 'Niña bonita' },
  { id: 16, name: 'Anillo' },
  { id: 17, name: 'Desgracia' },
  { id: 18, name: 'Sangre' },
  { id: 19, name: 'Pescado' },
  { id: 20, name: 'La fiesta' },
  { id: 21, name: 'La mujer' },
  { id: 22, name: 'El loco' },
  { id: 23, name: 'Mariposa' },
  { id: 24, name: 'Caballo' },
  { id: 25, name: 'Gallina' },
  { id: 26, name: 'La misa' },
  { id: 27, name: 'El peine' },
  { id: 28, name: 'El cerro' },
  { id: 29, name: 'San Pedro' },
  { id: 30, name: 'Santa Rosa' },
  { id: 31, name: 'La luz' },
  { id: 32, name: 'Dinero' },
  { id: 33, name: 'Cristo' },
  { id: 34, name: 'Cabeza' },
  { id: 35, name: 'Pajarito' },
  { id: 36, name: 'Manteca' },
  { id: 37, name: 'Dentista' },
  { id: 38, name: 'Aceite' },
  { id: 39, name: 'Lluvia' },
  { id: 40, name: 'Cura' },
  { id: 41, name: 'Cucha' },
  { id: 42, name: 'Zapatilla' },
  { id: 43, name: 'Balcón' },
  { id: 44, name: 'La cárcel' },
  { id: 45, name: 'El vino' },
  { id: 46, name: 'Tomates' },
  { id: 47, name: 'Muerto' },
  { id: 48, name: 'Muerto habla' },
  { id: 49, name: 'La carne' },
  { id: 50, name: 'El pan' },
  { id: 51, name: 'Serrucho' },
  { id: 52, name: 'Madre' },
  { id: 53, name: 'El barco' },
  { id: 54, name: 'La vaca' },
  { id: 55, name: 'Los gallegos' },
  { id: 56, name: 'La caída' },
  { id: 57, name: 'Jorobado' },
  { id: 58, name: 'Ahogado' },
  { id: 59, name: 'Planta' },
  { id: 60, name: 'Virgen' },
  { id: 61, name: 'Escopete' },
  { id: 62, name: 'Inundación' },
  { id: 63, name: 'Casamiento' },
  { id: 64, name: 'Llanto' },
  { id: 65, name: 'Cazador' },
  { id: 66, name: 'Lombrices' },
  { id: 67, name: 'Víbora' },
  { id: 68, name: 'Sobrinos' },
  { id: 69, name: 'Vicios' },
  { id: 70, name: 'Muerto sueños' },
  { id: 71, name: 'Excrementos' },
  { id: 72, a: 'Sorpresa' },
  { id: 73, name: 'Hospital' },
  { id: 74, name: 'Negros' },
  { id: 75, name: 'Payaso' },
  { id: 76, name: 'Llamas' },
  { id: 77, name: 'Las piernas' },
  { id: 78, name: 'Ramera' },
  { id: 79, name: 'Ladrón' },
  { id: 80, name: 'La bocha' },
  { id: 81, name: 'Flores' },
  { id: 82, name: 'Pelea' },
  { id: 83, name: 'Mal tiempo' },
  { id: 84, name: 'Iglesia' },
  { id: 85, name: 'Linterna' },
  { id: 86, name: 'Humo' },
  { id: 87, name: 'Piojos' },
  { id: 88, name: 'El Papa' },
  { id: 89, name: 'La rata' },
  { id: 90, name: 'El miedo' },
  { id: 91, name: 'Excusado' },
  { id: 92, name: 'Médico' },
  { id: 93, name: 'Enamorado' },
  { id: 94, name: 'Cementerio' },
  { id: 95, name: 'Anteojos' },
  { id: 96, name: 'Marido' },
  { id: 97, name: 'La mesa' },
  { id: 98, name: 'Lavandera' },
  { id: 99, name: 'Hermanos' },
];